name: Build and Release WinForms (.NET 10)

on:
  push:
    branches: dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Required for tagging

    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Setup .NET 10 SDK
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    # Restore packages
    - name: Restore packages
      run: dotnet restore MusicPlayer.csproj --runtime win-x64

    # Publish
    - name: Publish portable WinForms
      run: |
        dotnet publish MusicPlayer.csproj `
          -c Release `
          -r win-x64 `
          --self-contained `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:PublishTrimmed=false `
          -o bin/Release/net10.0-windows/win-x64/publish